Service:
  DeployType: ros
  DeployMetadata:
    SupplierDeployMetadata:
      SupplierTemplateConfigs:
        - Name: 选择ECS实例（Linux）
          Url: 
            https://service-info-private.oss-cn-hangzhou.aliyuncs.com/1853370294850618/template/5ff6c921-5eab-484e-ad82-cf0fb92be2c9.json
          PredefinedParameters: []
        - Name: 新建ECS实例
          Url: https://service-info-public.oss-cn-hangzhou.aliyuncs.com/1853370294850618/cn-hangzhou/template-create-ecsedbab72826d747d5b3f7.yaml
          PredefinedParameters: []
    TemplateConfigs:
      - Name: 选择ECS实例（Linux）
        Url: ros_templates/template-select-ecs.yaml
        PredefinedParameters: []
        DeployScene: ECS
        OutputConfigs:
          - OutputKey: __biubiu__
            EnableWebProxy: false
      - Name: 新建ECS实例
        Url: ros_templates/template-create-ecs.yaml
        PredefinedParameters: []
        DeployScene: ECS
    NetworkMetadata:
      EnablePrivateVpcConnection: false
      EnableReversePrivateVpcConnection: false
    ServiceInstanceNameRule:
      Prefix: python-
      UseDefaultValue: false
  OperationMetadata:
    SupportBackup: false
    PrometheusConfigMap:
      选择ECS实例（Linux）:
        EnablePrometheus: false
      新建ECS实例:
        EnablePrometheus: false
  ServiceType: private
  ServiceInfo:
    - Agreements: []
      Image: resources/icons/service_logo.png
      Locale: zh-CN
      Name: Python运行环境
      ShortDescription: Python是一种广泛使用的高级编程语言。Python的设计哲学强调代码的可读性以及一种简单直接的语法，这使得它成为一种广受欢迎的初学者学习语言，同时也被许多专业开发者用于大型项目的开发。
      Softwares:
        - Name: python
          Version: 3.6.8
  ShareType: Public
  ApprovalType: Manual
Artifact: {}
