Service:
  RegionId: cn-hangzhou
  DeployType: ros
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: Python-
    TemplateConfigs:
      - Name: 选择ECS实例（Linux）
        Url: 'ros_templates/template-select-ecs.yaml'
      - Name: 新建ECS实例
        Url: 'ros_templates/template-create-ecs.yaml'
  ServiceType: private
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: Python是一种广泛使用的高级编程语言。Python的设计哲学强调代码的可读性以及一种简单直接的语法，这使得它成为一种广受欢迎的初学者学习语言，同时也被许多专业开发者用于大型项目的开发。
    Image: 'resources/icons/service_logo.png'